port: 4000

theme: default

author: 

deploy:
 type: github
 repo: 
 branch: 
 message: Dimagen deploy

social:
 twitter: 
 github: 
 weibo: 

comments: true
duoshuo_shortname: dimagen

blogName: Dimagen!

blogUrl: 

